/*
******************************************************************************************************************
Apex Class Name     : KeyValuePair
Created Date        : February 9 2026
@description        : Structure to hold a Key Value pair
@author             : Ravi Raj
Modification Log    :
Ver   Date         Author           Modification
1.0   09-02-2026   Ravi Raj         Initial Version
******************************************************************************************************************
*/
public with sharing class KeyValuePair 
{
    public string Key;
    public string Value; 
}